name: Publish Docker image (Aliyun)

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Check out the repo
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3

      - name: Step2 - Log in to Docker Hub
        # https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Step3 - Extract metadata (tags, labels) for Docker
        id: meta
        # https://github.com/marketplace/actions/docker-metadata-action
        uses: docker/metadata-action@v4
        with:
          images: kc-docker-mirror/openjdk
          tags: 17.0.2-jdk

      - name: Step4 - Log in to Aliyun registry
        # https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v2
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Step5 - Build and push Docker image To Aliyun
        # https://github.com/marketplace/actions/build-and-push-docker-images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./openjdk/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
